package com.ykotsiuba.profitsoft_2.entity.enums;

public enum Field {
    PHYSICS, CHEMISTRY, ENGINEERING, ASTRONOMY, HISTORY, ECONOMICS, LINGUISTICS,
    BIOLOGY, MATHEMATICS, LITERATURE, COMPUTER_SCIENCE, PSYCHOLOGY, MEDICINE
}
